stages:
  - deploy
  - push-registry

variables:
  DOCKER_IMAGE: registry.adinusa.id/laraschool/laraschool-vian
  DOCKER_SERVICE: registry.adinusa.id/btacademy/docker:latest
  DOCKER_DIND: registry.adinusa.id/btacademy/docker:dind
deploy-laraschool:
  stage: deploy
  image: $DOCKER_SERVICE
  services:
    - $DOCKER_DIND

  script:
    - docker-compose down --rmi all
    - docker ps
    - cp .env.example .env
    - docker-compose build app
    - docker-compose up -d
    - docker ps

  after_script:
    - docker cp perpus.conf laraschool-nginx:/etc/nginx/conf.d/default.conf
    - docker exec laraschool-nginx mkdir -p /var/www
    - docker exec laraschool-nginx mkdir -p /var/www/html
    - docker cp . laraschool-nginx:/var/www/html
  only:
    - main

push-registry-laraschool:
  stage: push-registry
  image: $DOCKER_SERVICE
  services:
    - $DOCKER_DIND

  before_script:
    - echo -n $HARBOR_PASSWORD | docker login --username $HARBOR_USERNAME --password-stdin  $HARBOR_URL
    - docker info
  script:
    - docker push $DOCKER_IMAGE:1.0
  only:
    - main
